config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  resources :nfes

  devise_for :users
  
  resources :roles
  
  resources :senders
  
  resources :users

  get 'home/index'

  root to: "home#index"

end

app/models/invoice.rb
require "savon"
require "xmldsig"

class Invoice < ActiveRecord::Base
  belongs_to :sender
  
  before_save :sign_xml
  
  private
    def sign_xml
      key = Rails.root.join('private','certificates','teste_key.pem')
      cert = Rails.root.join('private','certificates','teste_cert.pem')
      xmldsig = XMLDSIG::signer_for_cert_files(cert, key, 'teste1234')
      
      self.signed_xml = xmldsig.sign! self.signed_xml
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:sender_id, :number, :series, :signed_xml)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper

end

app/views/invoices/_form.html.erb
<%= simple_form_for @invoice, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
  
  <%= f.association :sender %>
  <%= f.input :number %>
  <%= f.input :series %>
  <%= f.input :signed_xml %>

  <%= f.button :submit %>
<% end %>

app/views/invoices/edit.html.erb
<h1><%= t_editing_model :Invoice %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.show'), @invoice %> |
<%= link_to t('app.back'), invoices_path %>

app/views/invoices/index.html.erb
<h1><%= t_listing_model :invoice %></h1>

<div class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th><%= t_attr_model :invoice, :sender %></th>
        <th><%= t_attr_model :invoice, :number %></th>
        <th><%= t_attr_model :invoice, :series %></th>
        <th><%= t_attr_model :invoice, :signed_xml %></th>
        <th colspan="3" class="col-md-1"><%= t('app.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.sender %></td>
          <td><%= invoice.number %></td>
          <td><%= invoice.series %></td>
          <td><%= invoice.signed_xml %></td>
          <td><%= link_to t('app.show'), invoice %></td>
          <td><%= link_to t('app.edit'), edit_invoice_path(invoice) %></td>
          <td><%= link_to t('app.destroy'), invoice, method: :delete, data: { confirm: t('app.destroy_question') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to t_create_model(:invoice), new_invoice_path %>

app/views/invoices/new.html.erb
<h1><%= t_creating_model :invoice %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.back'), invoices_path %>

app/views/invoices/show.html.erb
<h1><%= t_showing_model :invoice %></h1>

<div class="panel panel-default">
  <div class="panel-body">
        <p>
      <strong><%= t_attr_model :invoice, :sender %>:</strong>
      <%= @invoice.sender %>
    </p>
        <p>
      <strong><%= t_attr_model :invoice, :number %>:</strong>
      <%= @invoice.number %>
    </p>
        <p>
      <strong><%= t_attr_model :invoice, :series %>:</strong>
      <%= @invoice.series %>
    </p>
        <p>
      <strong><%= t_attr_model :invoice, :signed_xml %>:</strong>
      <%= @invoice.signed_xml %>
    </p>
      </div>
</div>

<%= link_to t('app.edit'), edit_invoice_path(@invoice) %> |
<%= link_to t('app.back'), invoices_path %>