config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  resources :nfes

  devise_for :users
  
  resources :roles
  
  resources :senders
  
  resources :users

  get 'home/index'

  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_confirmation_of :password
  
  validates_presence_of :password_confirmation, :if => :password_changed?
  
  validates_presence_of :full_name, :email, :roles
  
  has_and_belongs_to_many :roles
  
  def password_changed?
    !@new_password.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    puts params.require(:user)
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: t_model_created(:user) }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if params[:user][:password].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end
      if @user.update(user_params)
        format.html { redirect_to @user, notice: t_model_updated(:user) }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t_model_destroyed(:user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:full_name, :email, :password, :password_confirmation, {:role_ids => []})
    end
end

app/views/users/_form.html.erb
<%= simple_form_for @user, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  
  <%= f.error_notification %>
  <%= f.input :full_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.association :roles, label_method: :name %>

  <%= f.button :submit %>

<% end %>

app/views/users/edit.html.erb
<h1><%= t_editing_model :user %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.show'), @user %> |
<%= link_to t('app.back'), users_path %>

app/views/users/index.html.erb
<h1><%= t_listing_model :user %></h1>

<div class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th><%= t_attr_model :user, :email %></th>
        <th><%= t_attr_model :user, :full_name %></th>
        <th colspan="3" class="col-md-1"><%= t('app.actions') %></th>
      </tr>
    </thead>
  
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.full_name %></td>
          <td><%= link_to t('app.show'), user %></td>
          <td><%= link_to t('app.edit'), edit_user_path(user) %></td>
          <td><%= link_to t('app.destroy'), user, method: :delete, data: { confirm: t('app.destroy_question') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to t_create_model(:user), new_user_path %>

app/views/users/new.html.erb
<h1><%= t_creating_model :user %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.back'), users_path %>

app/views/users/show.html.erb
<h1><%= t_showing_model :user %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <p><strong><%= t_attr_model :user, :full_name %>:</strong>
      <%= @user.full_name %>
    </p>
    <p><strong><%= t_attr_model :user, :email %>:</strong>
      <%= @user.email %>
    </p>
  </div>
</div>

<%= link_to t('app.edit'), edit_user_path(@user) %> |
<%= link_to t('app.back'), users_path %>