config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  resources :nfes

  devise_for :users
  
  resources :roles
  
  resources :senders
  
  resources :users

  get 'home/index'

  root to: "home#index"

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :permissions
  
  validates_presence_of :name
  
  validates_uniqueness_of :name
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include ApplicationHelper
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    puts params.require(:role)
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: t_model_created(:role) }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: t_model_updated(:role) }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: t_model_destroyed(:role) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, {:permission_ids => []})
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= simple_form_for @role, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.association :permissions, label_method: :permission_description %>

  <%= f.button :submit %>

<% end %>

app/views/roles/edit.html.erb
<h1><%= t_editing_model :role %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.show'), @role %> |
<%= link_to t('app.back'), roles_path %>

app/views/roles/index.html.erb
<h1><%= t_listing_model :role %></h1>

<div class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th><%= t_attr_model :role, :name %></th>
        <th colspan="3" class="col-md-1"><%= t('app.actions') %></th>
      </tr>
    </thead>
  
    <tbody>
      <% @roles.each do |role| %>
        <tr>
          <td><%= role.name %></td>
          <td><%= link_to t('app.show'), role %></td>
          <td><%= link_to t('app.edit'), edit_role_path(role) %></td>
          <td><%= link_to t('app.destroy'), role, method: :delete, data: { confirm: t('app.destroy_question') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to t_create_model(:role), new_role_path %>

app/views/roles/new.html.erb
<h1><%= t_creating_model :role %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.back'), roles_path %>

app/views/roles/show.html.erb
<h1><%= t_showing_model :role %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <p><strong><%= t_attr_model :role, :name %>:</strong>
      <%= @role.name %>
    </p>
  </div>
</div>

<%= link_to t('app.edit'), edit_role_path(@role) %> |
<%= link_to t('app.back'), roles_path %>