config/routes.rb
Rails.application.routes.draw do
  resources :invoices

  resources :nfes

  devise_for :users
  
  resources :roles
  
  resources :senders
  
  resources :users

  get 'home/index'

  root to: "home#index"

end

app/models/sender.rb
class Sender < ActiveRecord::Base
  validates_presence_of :name, :cnpj, :certificate
  validates_length_of :cnpj, maximum: 14
  validates_cnpj :cnpj
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  include ApplicationHelper
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  before_action :set_sender, only: [:show, :edit, :update, :destroy]

  # GET /senders
  # GET /senders.json
  def index
    @senders = Sender.all
  end

  # GET /senders/1
  # GET /senders/1.json
  def show
  end

  # GET /senders/new
  def new
    @sender = Sender.new
  end

  # GET /senders/1/edit
  def edit
  end

  # POST /senders
  # POST /senders.json
  def create
    @sender = Sender.new(sender_params)

    respond_to do |format|
      if @sender.save
        format.html { redirect_to @sender, notice: 'Sender was successfully created.' }
        format.json { render :show, status: :created, location: @sender }
      else
        format.html { render :new }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /senders/1
  # PATCH/PUT /senders/1.json
  def update
    respond_to do |format|
      if @sender.update(sender_params)
        format.html { redirect_to @sender, notice: 'Sender was successfully updated.' }
        format.json { render :show, status: :ok, location: @sender }
      else
        format.html { render :edit }
        format.json { render json: @sender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /senders/1
  # DELETE /senders/1.json
  def destroy
    @sender.destroy
    respond_to do |format|
      format.html { redirect_to senders_url, notice: 'Sender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sender
      @sender = Sender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sender_params
      params.require(:sender).permit(:name, :cnpj, :certificate, :nfe_sender)
    end
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/_form.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<%= simple_form_for @sender, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
  
  <%= f.input :name %>
  <%= f.input :cnpj, :input_html => {:maxlength => 14} %>
  <%= f.input :certificate, wrapper: :horizontal_server_file_chooser  %>
  <%= f.input :nfe_sender %>
  
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" type="button">
  Launch demo modal
</button>

  <%= f.button :submit %>
<% end %>

app/views/senders/edit.html.erb
<h1><%= t_editing_model :Sender %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.show'), @sender %> |
<%= link_to t('app.back'), senders_path %>

app/views/senders/index.html.erb
<h1><%= t_listing_model :sender %></h1>

<div class="panel panel-default">
  <table class="table">
    <thead>
      <tr>
        <th><%= t_attr_model :sender, :name %></th>
        <th><%= t_attr_model :sender, :cnpj %></th>
        <th><%= t_attr_model :sender, :certificate %></th>
        <th><%= t_attr_model :sender, :nfe_sender %></th>
        <th colspan="3" class="col-md-1"><%= t('app.actions') %></th>
      </tr>
    </thead>

    <tbody>
      <% @senders.each do |sender| %>
        <tr>
          <td><%= sender.name %></td>
          <td><%= sender.cnpj %></td>
          <td><%= sender.certificate %></td>
          <td><%= sender.nfe_sender %></td>
          <td><%= link_to t('app.show'), sender %></td>
          <td><%= link_to t('app.edit'), edit_sender_path(sender) %></td>
          <td><%= link_to t('app.destroy'), sender, method: :delete, data: { confirm: t('app.destroy_question') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to t_create_model(:sender), new_sender_path %>

app/views/senders/new.html.erb
<h1><%= t_creating_model :sender %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to t('app.back'), senders_path %>

app/views/senders/show.html.erb
<h1><%= t_showing_model :sender %></h1>

<div class="panel panel-default">
  <div class="panel-body">
        <p>
      <strong><%= t_attr_model :sender, :name %>:</strong>
      <%= @sender.name %>
    </p>
        <p>
      <strong><%= t_attr_model :sender, :cnpj %>:</strong>
      <%= @sender.cnpj %>
    </p>
        <p>
      <strong><%= t_attr_model :sender, :certificate %>:</strong>
      <%= @sender.certificate %>
    </p>
        <p>
      <strong><%= t_attr_model :sender, :nfe_sender %>:</strong>
      <%= @sender.nfe_sender %>
    </p>
      </div>
</div>

<%= link_to t('app.edit'), edit_sender_path(@sender) %> |
<%= link_to t('app.back'), senders_path %>